# Model parameters
sumO: True
# Training parameters
epochs: 250
bs: 64
lr: 0.001
wd: 0.001
# loss_function: "crossentropyloss"
# optimizer: "AdamW"
lr_schedule: "onecycle"  # onecycle, cosinedecay, constant
# Dataset
data_dir: "../data/hls4ml_LHCjet_150p/hls4ml_LHCjet_150p_JEDI"
dataset_class: "JEDIDataset"
train_size: 630000
val_size: 260000
# Other
device: "cuda"
dataloader_num_workers: 2
